import type { CSSProperties } from "react";

export const S: Record<string, CSSProperties> = {
  container: {
    minHeight: "100vh",
    backgroundColor: "#F5F3EE",
    padding: "20px 12px 48px",
    fontFamily: "'Noto Sans TC', 'Microsoft JhengHei', sans-serif",
    boxSizing: "border-box",
  },
  card: {
    maxWidth: 600,
    margin: "0 auto",
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    boxShadow: "0 6px 32px rgba(0,0,0,0.10), 0 1px 4px rgba(0,0,0,0.05)",
    padding: "8px 20px 28px",
  },
  goldAccent: {
    height: 5,
    background: "linear-gradient(90deg, #C8860A 0%, #F59E0B 50%, #C8860A 100%)",
    margin: "0 -20px 24px",
  },
  header: {
    marginBottom: 28,
    borderBottom: "1.5px solid #E2E8F0",
  },
  title: {
    margin: "0 0 6px",
    fontSize: 28,
    fontWeight: 800,
    color: "#1E3A5F",
    letterSpacing: 1,
  },
  subtitle: { margin: 0, fontSize: 14, color: "#64748B" },
  section: { marginBottom: 24 },
  label: {
    display: "block",
    fontWeight: 700,
    fontSize: 15,
    color: "#374151",
    marginBottom: 10,
  },
  select: {
    width: "100%",
    padding: "14px 16px",
    fontSize: 16,
    borderRadius: 10,
    border: "1.5px solid #CBD5E1",
    backgroundColor: "#F8FAFC",
    color: "#1E293B",
    outline: "none",
    boxSizing: "border-box",
  },
  textInput: {
    width: "100%",
    padding: "14px 16px",
    fontSize: 16,
    borderRadius: 10,
    border: "1.5px solid #CBD5E1",
    backgroundColor: "#F8FAFC",
    color: "#1E293B",
    outline: "none",
    boxSizing: "border-box",
  },
  orDivider: { display: "flex", alignItems: "center", gap: 12, marginBottom: 24 },
  orLine: { flex: 1, height: 1, backgroundColor: "#E2E8F0", display: "block" },
  orText: { fontSize: 13, color: "#94A3B8", fontWeight: 600, whiteSpace: "nowrap" },
  tableHeadingRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  legendToggle: {
    padding: "6px 12px",
    fontSize: 12,
    color: "#6D28D9",
    background: "#F5F3FF",
    border: "1px solid #DDD6FE",
    borderRadius: 99,
    cursor: "pointer",
    fontFamily: "inherit",
    fontWeight: 600,
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  tableHeader: {
    display: "flex",
    alignItems: "center",
    padding: "6px 8px 0",
    backgroundColor: "#F8FAFC",
    borderRadius: "10px 10px 0 0",
  },
  tableSubHeader: {
    display: "flex",
    alignItems: "center",
    padding: "4px 8px 6px",
    backgroundColor: "#F8FAFC",
    borderBottom: "2px solid #E2E8F0",
    textAlign: "center",
  },
  sessionGroupLabel: {
    flex: 3,
    textAlign: "center",
    fontSize: 11,
    fontWeight: 700,
    color: "#94A3B8",
    letterSpacing: 1,
    paddingBottom: 2,
    borderBottom: "1.5px solid #E2E8F0",
  },
  specialGroupLabel: {
    color: "#7C3AED",
    borderBottom: "1.5px solid #C4B5FD",
    background: "linear-gradient(to right, #F5F3FF, #EDE9FE)",
    borderRadius: "4px 4px 0 0",
    padding: "2px 0",
  },
  nameCol: {
    flex: "0 0 65px" as CSSProperties["flex"],
    fontWeight: 600,
    color: "#1E293B",
    fontSize: 14,
  },
  sessionCol: { flex: 1 },
  specialColHeader: {},
  tableBody: {
    maxHeight: 480,
    overflowY: "auto",
    border: "1px solid #E2E8F0",
    borderTop: "none",
  },
  progressBar: {
    padding: "14px 16px",
    background: "linear-gradient(135deg, #F5F3FF 0%, #EDE9FE 100%)",
    borderRadius: "0 0 10px 10px",
    border: "1px solid #DDD6FE",
    borderTop: "none",
  },
  progressInner: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "baseline",
    marginBottom: 8,
  },
  progressLabel: { fontSize: 13, fontWeight: 700, color: "#6D28D9" },
  progressPct: {
    fontSize: 36,
    fontWeight: 800,
    color: "#4C1D95",
    letterSpacing: -1,
    lineHeight: 1,
  },
  progressTrack: {
    height: 8,
    backgroundColor: "#DDD6FE",
    borderRadius: 99,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    background: "linear-gradient(to right, #8B5CF6, #6D28D9)",
    borderRadius: 99,
    transition: "width 0.4s ease",
  },
  textarea: {
    width: "100%",
    padding: "14px 16px",
    fontSize: 15,
    borderRadius: 10,
    border: "1.5px solid #CBD5E1",
    backgroundColor: "#F8FAFC",
    color: "#1E293B",
    resize: "vertical",
    outline: "none",
    boxSizing: "border-box",
    fontFamily: "inherit",
    lineHeight: 1.6,
  },
  submitBtn: {
    width: "100%",
    padding: "18px 24px",
    fontSize: 18,
    fontWeight: 800,
    border: "none",
    borderRadius: 12,
    letterSpacing: 1,
    transition: "all 0.3s ease",
    marginTop: 4,
  },
};
